CREATE TABLE airflow.subway_congestion (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    SUBWAY_DIVISION VARCHAR(100) NOT NULL,
    STATION_NO INT(11) NOT NULL,
    STATION_NAME VARCHAR(100) NOT NULL,
	SERIAL_NO INT(11) NOT NULL,
    SUBWAY_LINE INT(11) NOT NULL,
    OPERATION_TIME VARCHAR(30) NOT NULL,
    CONGETSTION VARCHAR(10) NOT NULL,
    PRIMARY KEY(ID)
);